workspace:
  base: /usr/local/src
  path: github.com/qnib/go-netcollect/

pipeline:
  alpine:
    image: qnib/alplain-golang:1.9
    commands:
      - /usr/local/go/bin/go build -o ./bundle/go-netcollect_Alpine
  x86:
    image: qnib/uplain-golang
    commands:
      - go build -o ./bundle/go-netcollect_x86
